### ISSUE TITLE
Unable to read coordinates files of custom molecule

### ISSUE THREAD

**Issue by marcodigennaro** [paduagroup/fftool#13]
I have tried to read a molecule with fftool and in several data formats but I encounter several issues:
The molecule is TFSI:
```
16

C          6.03034        4.09220        5.48886
F          5.37202        5.30065        5.36546
F          6.39135        3.89541        6.80769
F          7.16406        4.10454        4.69920
N          3.42469        2.54403        5.86881
C          0.86033        0.89196        5.97521
F          0.03319        0.14152        5.16196
F          0.14535        1.94693        6.50866
F          1.34449        0.09819        6.99698
S          4.93349        2.75026        4.95267
S          2.24665        1.53550        4.99964
O          5.62532        1.37952        5.01298
O          4.53998        2.86277        3.47122
O          1.78341        2.37997        3.80211
O          3.05533        0.41678        4.32326
H          3.00037        3.48797        6.01118
```
I created a `.pdb` and a `.gzmat` extension with obabel and a `.zmat` extension with molden. All give different errors.

```
$ fftool 10 files/TFSI.xyz -r 10
> density 10.000 mol/L  volume 1660.6 A^3
> molecule_file      species           nmol force_field      nbond source  charge
> Traceback (most recent call last):
  File "/Users/marcodigennaro/WORK/external_packages/fftool/fftool", line 2816, in <module>
    main()
  File "/Users/marcodigennaro/WORK/external_packages/fftool/fftool", line 2768, in main
    spec.append(mol(zfile, connect, box))
  File "/Users/marcodigennaro/WORK/external_packages/fftool/fftool", line 615, in __init__
    self.fromxyz(filename, connect, box)
  File "/Users/marcodigennaro/WORK/external_packages/fftool/fftool", line 882, in fromxyz
    self.name = tok[0]            # molecule name
IndexError: list index out of range
```

```
$ fftool 10 files/TFSI.pdb -r 10
> density 10.000 mol/L  volume 1660.6 A^3
> molecule_file      species           nmol force_field      nbond source  charge
>  warning: no force field for TFSI
> Traceback (most recent call last):
  File "/Users/marcodigennaro/WORK/external_packages/fftool/fftool", line 2816, in <module>
    main()
  File "/Users/marcodigennaro/WORK/external_packages/fftool/fftool", line 2772, in main
    .format(zfile, spec[i].name, spec[i].nmol, spec[i].ffile,
TypeError: unsupported format string passed to NoneType.__format__
```

```
$ fftool 10 files/TFSI.zmat -r 10
> density 10.000 mol/L  volume 1660.6 A^3
> molecule_file      species           nmol force_field      nbond source  charge
> Traceback (most recent call last):
  File "/Users/marcodigennaro/WORK/external_packages/fftool/fftool", line 2816, in <module>
    main()
  File "/Users/marcodigennaro/WORK/external_packages/fftool/fftool", line 2768, in main
    spec.append(mol(zfile, connect, box))
  File "/Users/marcodigennaro/WORK/external_packages/fftool/fftool", line 611, in __init__
    self.fromzmat(filename, connect)
  File "/Users/marcodigennaro/WORK/external_packages/fftool/fftool", line 696, in fromzmat
    self.zmat2cart(z)
  File "/Users/marcodigennaro/WORK/external_packages/fftool/fftool", line 754, in zmat2cart
    theta = math.acos(delx / math.sqrt(delx*delx + dely*dely))
ZeroDivisionError: float division by zero
```

How to get the right zmat format? In the example folder some files (eg. ethane) have leading atom index:
```
ethane

1  C3H
2  C3H  1  rCC
3  H    2  rCH  1  aHCC
4  H    1  rCH  2  aHCC  3   d1
5  H    2  rCH  1  aHCC  4   d2
6  H    1  rCH  2  aHCC  5   d1
7  H    2  rCH  1  aHCC  6   d2
8  H    1  rCH  2  aHCC  7   d1
...
```

others (eg. benzene) do not:
```
benzene

CA
CA  1  rCC
CA  2  rCC  1  120.00
CA  3  rCC  2  120.00  1   0
CA  4  rCC  3  120.00  2   0
CA  5  rCC  4  120.00  3   0
HA  1  rCH  2  120.00  3 180
HA  2  rCH  3  120.00  4 180
HA  3  rCH  4  120.00  5 180
HA  4  rCH  5  120.00  6 180
HA  5  rCH  6  120.00  1 180
HA  6  rCH  1  120.00  2 180
...
```

What is the correct format and how to obtain it?
In my case, I don't know the atom types in advance (TFSI is just and example). 
Thank you

**Comment by agiliopadua** [comment]
If you start from an xyz file created by a tool such as Avogadro, then you need to edit it to add two things before you can use it with fftool:
1. Provide the name of the file where the force field parameters are to be found (in the second line of the xyz file)
2. Identify the atom types as they are defined in the force field (so each atom will have its partial charge, LJ parameters, bonded terms are found, etc.)
For TFSI = Ntf2 you can look at the example in the [clandp](https://github.com/paduagroup/clandp) repository. 

You'll need a reasonably optimised structure in the xyz, in order for the covalent bonds (topology) to be identified. So you need to check that the number of bonds reported by fftool is correct. If you start from a zmat, then the topology (bonds) is assumed from the 2 first columns (which atoms are bonded to which).

**Comment by marcodigennaro** [comment]
What software can I use to visualize this zmat format? I tried Avogadro (2), VMD and I have now spent quite some times trying to install molden and webmo without success. I can modify the file by hand but I have several molecules and it'd be great to have an automatic tool. 
Thanks

**Comment by marcodigennaro** [comment]
For xyz files, I need to supply the molecule name _and_ the force field file.
If I don't, the force field will not be recognized (`warning: no force field for Li-TFSI`) and the `mol` instance will not have the `ffile` attribute (`spec[i].ffile` -> `TypeError: unsupported format string passed to NoneType.__format__`)

Thus the correct format seems to be this:

```
16
Li-TFSI    il.ff   #Molecule name and force filed file
CBT        0.86105        0.89295        5.97469
CBT        6.02957        4.09250        5.48800
F1         0.03356        0.14224        5.16180
F1         0.14549        1.94748        6.50829
F1         1.34432        0.09869        6.99662
F1         5.37125        5.30088        5.36485
F1         6.39115        3.89604        6.80688
F1         7.16352        4.10471        4.69862
Li         2.18291        2.36466        8.39555
NBT        3.41917        2.55574        5.86439
OBT        1.78032        2.37959        3.80347
OBT        3.05925        0.41688        4.32394
OBT        4.54153        2.86457        3.47237
OBT        5.62154        1.37603        5.01432
SBT        2.24914        1.53537        4.99852
SBT        4.93368        2.74857        4.95398
```

**Comment by marcodigennaro** [comment]
This could help to transcribe `xyz` -> `zmat`
https://github.com/robashaw/geomConvert/tree/master

**Comment by agiliopadua** [comment]
If you revert back to just chemical element names in the zmat and remove the extra lines with the force field file (and maybe also the 1st column with atom number), then Avogadro should be able to visualise this. The surest way is to comply to the Gaussian z-matrix format.

**Comment by agiliopadua** [comment]
In general, you need to be able to edit files quickly and efficiently. Conversion tools stick to "standard" formats and only allow you to go so far.
